kind: Service                             
apiVersion: v1
metadata:
  name: complete
  labels:
    app: complete
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: complete                    
  type: LoadBalancer                   
